#!/usr/bin/env python3
def main():
	import sys
	text = sys.argv[1]
	pk_codes = [convert_code(ord(c)) for c in text]
	for code in pk_codes:
		print(code, end=' ')
	print()

PK_CAPITAL_A_OFFSET = 0xbb
PK_CAPITAL_Z_OFFSET = 0xd4

PK_LOWER_A_OFFSET = 0xd5
PK_LOWER_Z_OFFSET = 0xee

PK_ZERO_OFFSET = 0xa1
PK_NINE_OFFSET = 0xaa

def convert_code(ascii_code):
	pkcode = 0
	if ascii_code >= ord('a') and ascii_code <= ord('z'):
		pkcode = (ascii_code - ord('a')) + PK_LOWER_A_OFFSET
	elif ascii_code >= ord('A') and ascii_code <= ord('Z'):
		pkcode = (ascii_code - ord('A')) + PK_CAPITAL_A_OFFSET
	elif ascii_code >= ord('0') and ascii_code <= ord('9'):
		pkcode = (ascii_code - ord('0')) + PK_ZERO_OFFSET

	if pkcode:
		return f'{pkcode:02x}'
	return '??'

if __name__ == '__main__':
	main()
